// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.8_linklibpythonOption_ldreplace"
	GitCommit   = "3e58b56"          // the commit JUST BEFORE the release
	VersionDate = "2024-02-15 14:34" // UTC
)
