// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.8_linklibpythonOption"
	GitCommit   = "979d9ed"          // the commit JUST BEFORE the release
	VersionDate = "2024-02-13 22:22" // UTC
)
