// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.9"
	GitCommit   = "7e503c8"          // the commit JUST BEFORE the release
	VersionDate = "2024-02-13 22:00" // UTC
)
